name: Semantic Pull Request

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  # Allowed PR types: https://github.com/commitizen/conventional-commit-types/blob/master/index.json
  check:
    runs-on: ubuntu-latest
    steps:
      - name: semantic-pull-request
        # This action can only be invoked in `pull_request_target` or `pull_request` events.
        uses: amannn/action-semantic-pull-request@v5.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
